# Generated by Django 3.2.13 on 2023-10-20 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of book', max_length=150, verbose_name='Name')),
                ('author', models.CharField(help_text='Author of book', max_length=150, verbose_name='Author')),
                ('date_of_publication', models.DateField(help_text='Author of book', verbose_name='Date of publication of book')),
                ('short_description', models.CharField(help_text='Short description of book', max_length=150, verbose_name='Short description')),
                ('full_description', models.TextField(help_text='Full description of book', validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Full description')),
            ],
        ),
    ]
