# Generated by Django 3.2.13 on 2023-10-20 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booktimetracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_reading_session', models.DateTimeField(auto_now_add=True, verbose_name='Start of reading')),
                ('end_reading_session', models.DateTimeField(null=True, verbose_name='End of reading')),
                ('duration_of_session', models.DurationField(null=True, verbose_name='Duration of reading session')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booktimetracker.book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
